export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'nodes',
    path: '/node',
    title: 'nodes',
    requiresAuth: true,
    icon: 'carbon:radio-button-checked',
    componentPath: '/node/index.vue',
    id: 1,
    pid: null,
  },
  {
    name: 'users',
    path: '/user',
    title: 'users',
    requiresAuth: true,
    icon: 'carbon:user-avatar-filled',
    componentPath: '/user/index.vue',
    id: 2,
    pid: null,
  },
  {
    name: 'routes',
    path: '/route',
    title: 'routes',
    requiresAuth: true,
    icon: 'local:route',
    componentPath: '/route/index.vue',
    id: 2,
    pid: null,
  },
  {
    name: 'apiKeys',
    path: '/apiKey',
    title: 'apiKeys',
    requiresAuth: true,
    icon: 'carbon:api-key',
    componentPath: '/apiKey/index.vue',
    id: 2,
    pid: null,
  },
  {
    name: 'policy',
    path: '/policy',
    title: 'policy',
    requiresAuth: true,
    icon: 'carbon:vpn-policy',
    componentPath: '/policy/index.vue',
    id: 2,
    pid: null,
  },
]
