name: Build Docker Image

on:
  workflow_dispatch:
  release:
    types: [published]
    tags: [v*]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20.14.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0

      - name: Build
        run: npm run build

      - name: Extract project version from package.json
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_IO_USERNAME }}
          password: ${{ secrets.GHCR_IO_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jmal/headscale-webui:${{ env.PROJECT_VERSION }},jmal/headscale-webui:latest
            ghcr.io/${{ secrets.GHCR_IO_USERNAME }}/headscale-webui:${{ env.PROJECT_VERSION }},ghcr.io/${{ secrets.GHCR_IO_USERNAME }}/headscale-webui:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.PROJECT_VERSION }}
